export type GroupsSettingsMatrixEntry = {
  setting: string;
  module: string;
  expectedEffect: string;
  testId: string;
  linkage: "runtime" | "derived";
};

export const GROUPS_SETTINGS_MATRIX: GroupsSettingsMatrixEntry[] = [
  {
    setting: "settings.groups.storage.mode",
    module: "groups-v1/storage/resolveStorageMode.ts",
    expectedEffect: "Seleciona o runtime final (cloud, local_device, chosen_folder, hybrid).",
    testId: "settings-influence-storage-runtime",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.provider + baseFolderPath",
    module: "groups-v1/storage/resolveStorageMode.ts",
    expectedEffect: "Define a bridge legacy de anexos e o base path efetivo do provider final.",
    testId: "settings-influence-storage-runtime",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.localDevice.rootPath",
    module: "server/src/groupStorageRuntime.js",
    expectedEffect: "Valida e usa o root path real do modo local_device.",
    testId: "server-storage-local-device",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.chosenFolder.path",
    module: "server/src/groupStorageRuntime.js",
    expectedEffect: "Valida e usa o path manual real do modo chosen_folder.",
    testId: "server-storage-chosen-folder",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.chosenFolder.kind",
    module: "groups-v1/storage/resolveStorageMode.ts + server/src/groupStorageRuntime.js",
    expectedEffect: "Bloqueia document_library/web URL e permite apenas filesystem no perimetro aprovado.",
    testId: "server-storage-web-url-blocked",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.hybrid.primaryTarget",
    module: "groups-v1/storage/resolveStorageMode.ts + server/src/groupStorageRuntime.js",
    expectedEffect: "Escolhe o alvo principal local do modo hybrid.",
    testId: "server-storage-hybrid",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.ignoreInlineAttachments",
    module: "groups-v1/storage/attachmentPolicy.ts",
    expectedEffect: "Ignora anexos inline no plano local de anexos.",
    testId: "settings-influence-attachment-policy",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.attachmentPromptThresholdMb",
    module: "groups-v1/storage/attachmentPolicy.ts",
    expectedEffect: "Muda o threshold que pede decisao manual para anexos grandes.",
    testId: "settings-influence-attachment-policy",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.storage.supabase.promoteManifestOnSave / promoteAttachmentMetadataOnSave / promoteAttachmentBinaryOnSave",
    module: "groups-v1/storage/promotionPolicy.ts + buildPrepareWorksetManifest.ts",
    expectedEffect: "Altera a politica de promocao remota em cloud.",
    testId: "workset-cloud-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.groupsTabEnabled",
    module: "modules/crm/GroupsPrepareCockpit.tsx",
    expectedEffect: "Bloqueia o fluxo Preparar quando a aba Groups esta desligada.",
    testId: "settings-groups-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.storageMode",
    module: "groups-v1/storage/resolveIntermediateCaseStorage.ts",
    expectedEffect: "Liga IndexedDB local ou desliga o intermédio.",
    testId: "prepare-storage-disabled",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.baseFolderPath",
    module: "groups-v1/storage/resolveIntermediateCaseStorage.ts + resolveClassificationIntermediateCase.ts",
    expectedEffect: "Define o namespace do IndexedDB usado por Preparar/Classificar/reabertura.",
    testId: "classification-reopen-and-rehydrate",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.cleanupClosedCaseDays / cleanupAbandonedCaseDays / neverDeleteMixedSilently",
    module: "groups-v1/storage/intermediateCaseMaintenance.ts",
    expectedEffect: "Controla a limpeza real dos casos intermédios.",
    testId: "cleanup-retention-and-mixed-protection",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.migrationTarget / migrationMode / allowMoveExistingData / strictMigrationSafety / mergeExistingData",
    module: "groups-v1/storage/intermediateCaseMaintenance.ts",
    expectedEffect: "Controla a migracao real entre namespaces, incluindo gates de seguranca.",
    testId: "migration-copy-and-safety",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.autoCreateCaseOnNewEmail / reopenExistingCase / recreateIntermediateCopy",
    module: "modules/crm/GroupsPrepareCockpit.tsx + groups-v1/storage/resolveClassificationIntermediateCase.ts + groups-v1/settings/groupsTabRuntime.ts",
    expectedEffect: "Controla auto-criacao de checkpoint, reabertura automatica e projeccao do historico remoto para o intermédio.",
    testId: "settings-tab-case-behavior",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.validateLocationOnOpen / blockTabIfUnavailable / warnIfUnavailable / autoRetryValidation",
    module: "modules/crm/GroupsPrepareCockpit.tsx + groups-v1/storage/resolveClassificationIntermediateCase.ts + groups-v1/settings/groupsTabRuntime.ts",
    expectedEffect: "Controla validacao real do namespace, bloqueio da aba, aviso funcional e tentativa adicional de revalidacao.",
    testId: "settings-tab-storage-validation",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.attachmentStrategy / saveAttachmentsOnServer / saveAttachmentsOutsideServer / attachmentServerLimitMb / attachmentIntermediateLimitMb / externalAttachmentFolder / showAttachmentMetadataOnServer / requireImmediatePreview",
    module: "modules/crm/GroupsPrepareCockpit.tsx + group-classification/documentUtils.ts + groups-v1/settings/groupsTabRuntime.ts",
    expectedEffect: "Controla selecao por defeito, destino final, metadata/binario e preview imediato dos anexos do modulo Groups.",
    testId: "settings-tab-attachment-runtime",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.mixedCaseWarningDays / localAbandonedWarningDays / cleanupFrequency / warnUnclassifiedEmails / warnMixedCases / warningFrequency",
    module: "modules/crm/GroupsPrepareCockpit.tsx + groups-v1/storage/intermediateCaseMaintenance.ts + groups-v1/settings/groupsTabRuntime.ts",
    expectedEffect: "Controla warnings locais do cockpit e a cadencia da limpeza real do intermédio.",
    testId: "settings-tab-warning-runtime",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.prepareTasksBridge",
    module: "modules/crm/GroupsPrepareCockpit.tsx + groups-v1/prepareSession.ts",
    expectedEffect: "Controla a ponte local de contexto entre Preparar e Classificar.",
    testId: "settings-tab-prepare-bridge",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tab.explorerServerPrimary / explorerOpenStoredAttachments / explorerGenerateReply",
    module: "modules/crm/GroupClassificationStudioApp.tsx + groups-v1/settings/groupsTabRuntime.ts",
    expectedEffect: "Controla a precedencia server/intermedio e as acoes de abrir anexos guardados e gerar resposta/reenvio no studio.",
    testId: "settings-tab-explorer-bridges",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.labels.managerEnabled",
    module: "modules/crm/GroupManagerCockpit.tsx",
    expectedEffect: "Mantem o manager de labels governado pelo modulo Groups.",
    testId: "settings-groups-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.labels.catalog",
    module: "office.ts + GroupClassificationStudioApp.tsx + GroupManagerCockpit.tsx",
    expectedEffect: "Alimenta o catalogo de etiquetas usado pelo studio e pelas categorias Outlook.",
    testId: "settings-influence-outlook-categories",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.labels.favoriteIds",
    module: "modules/crm/GroupClassificationStudioApp.tsx",
    expectedEffect: "Persiste favoritos de etiquetas do studio dentro da arvore canonica de Groups.",
    testId: "settings-groups-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tickets.enabled",
    module: "modules/crm/GroupManagerCockpit.tsx",
    expectedEffect: "Liga/desliga o runtime de tickets do modulo Groups.",
    testId: "settings-groups-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.tickets.ui.autoLinkMode / suggestDraftOnCreate / useAiDrafts / includeTicketCodeInSubject / aiInstructions",
    module: "modules/crm/GroupManagerCockpit.tsx + modules/ai/AiCockpit.tsx",
    expectedEffect: "Mantem a configuracao de UX/tickets de Groups sob a fonte canonica do modulo.",
    testId: "settings-groups-roundtrip",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.outlookCategories.enabled",
    module: "outlookCategories.ts + group-classification/outlookCategoryApply.ts",
    expectedEffect: "Liga/desliga o plano logico de categorias Outlook para Grupos.",
    testId: "settings-influence-outlook-categories",
    linkage: "runtime",
  },
  {
    setting: "settings.groups.outlookCategories.includeGroups / includeTickets / includeStatuses / includeLabels",
    module: "outlookCategories.ts",
    expectedEffect: "Seleciona que familias entram no plano logico de categorias Outlook.",
    testId: "settings-influence-outlook-categories",
    linkage: "runtime",
  },
];
